export const LL2_PRODUCTION_BASE_URL = "https://ll.thespacedevs.com/2.3.0/";
export const LL2_DEVELOPMENT_BASE_URL = "https://lldev.thespacedevs.com/2.3.0/";

export const LL2_ENDPOINTS = Object.freeze({
  agencies: "agencies", astronauts: "astronauts", celestialBodies: "celestial_bodies", dockingEvents: "docking_events", events: "events", expeditions: "expeditions", landings: "landings", launches: "launches", launchers: "launchers", launcherConfigurations: "launcher_configurations", launcherConfigurationFamilies: "launcher_configuration_families", locations: "locations", missionPatches: "mission_patches", pads: "pads", payloadFlights: "payload_flights", payloads: "payloads", programs: "programs", spacecraft: "spacecraft", spacecraftConfigurations: "spacecraft_configurations", spacecraftConfigurationFamilies: "spacecraft_configuration_families", spacecraftFlights: "spacecraft_flights", spaceStations: "space_stations", spacewalks: "spacewalks", updates: "updates",
});

export const LL2_CONFIG_ENDPOINTS = Object.freeze({
  agencyTypes: "config/agency_types", astronautRoles: "config/astronaut_roles", astronautStatuses: "config/astronaut_statuses", astronautTypes: "config/astronaut_types", celestialBodyTypes: "config/celestial_body_types", countries: "config/countries", dockingLocations: "config/docking_locations", eventTypes: "config/event_types", firstStageTypes: "config/first_stage_types", imageLicenses: "config/image_licenses", imageVariantTypes: "config/image_variant_types", infoUrlTypes: "config/infourl_types", landingLocations: "config/landing_locations", landingTypes: "config/landing_types", languages: "config/languages", launchStatuses: "config/launch_statuses", launcherStatuses: "config/launcher_statuses", missionTypes: "config/mission_types", netPrecisions: "config/net_precisions", noticeTypes: "config/notice_types", orbits: "config/orbits", payloadTypes: "config/payload_types", programTypes: "config/program_types", roadClosureStatuses: "config/road_closure_statuses", spacecraftConfigurationTypes: "config/spacecraft_configuration_types", spacecraftStatuses: "config/spacecraft_statuses", spaceStationStatuses: "config/space_station_statuses", timelineEventTypes: "config/timeline_event_types", videoUrlTypes: "config/vidurl_types",
});
