export const sum = (values: readonly number[]): number => values.reduce((a, b) => a + b, 0);
export const mean = (values: readonly number[]): number => values.length ? sum(values) / values.length : Number.NaN;
export function variance(values: readonly number[], sample = false): number { if (values.length <= (sample ? 1 : 0)) return Number.NaN; const m = mean(values); return values.reduce((s, x) => s + (x - m) ** 2, 0) / (values.length - (sample ? 1 : 0)); }
export const stddev = (values: readonly number[], sample = false): number => Math.sqrt(variance(values, sample));
export function percentile(values: readonly number[], p: number): number { if (!values.length) return Number.NaN; const sorted = [...values].sort((a, b) => a - b); const idx = Math.max(0, Math.min(1, p)) * (sorted.length - 1); const lo = Math.floor(idx), hi = Math.ceil(idx), t = idx - lo; return (sorted[lo] ?? 0) * (1 - t) + (sorted[hi] ?? 0) * t; }
export const median = (values: readonly number[]): number => percentile(values, 0.5);
export function covariance(a: readonly number[], b: readonly number[], sample = false): number { const n = Math.min(a.length, b.length); if (n <= (sample ? 1 : 0)) return Number.NaN; const ma = mean(a.slice(0, n)), mb = mean(b.slice(0, n)); let s = 0; for (let i = 0; i < n; i++) s += ((a[i] ?? 0) - ma) * ((b[i] ?? 0) - mb); return s / (n - (sample ? 1 : 0)); }
export const correlation = (a: readonly number[], b: readonly number[]): number => covariance(a, b) / (stddev(a) * stddev(b));
export function linearRegression(x: readonly number[], y: readonly number[]): { slope: number; intercept: number; r2: number } { const n = Math.min(x.length, y.length); const xs = x.slice(0, n), ys = y.slice(0, n); const slope = covariance(xs, ys) / variance(xs); const intercept = mean(ys) - slope * mean(xs); const predictions = xs.map((v) => intercept + slope * v); const ssRes = ys.reduce((s, v, i) => s + (v - (predictions[i] ?? 0)) ** 2, 0); const my = mean(ys); const ssTot = ys.reduce((s, v) => s + (v - my) ** 2, 0); return { slope, intercept, r2: ssTot === 0 ? 1 : 1 - ssRes / ssTot }; }
export function gaussianRandom(meanValue = 0, standardDeviation = 1, random = Math.random): number { const u1 = Math.max(Number.EPSILON, random()), u2 = random(); return meanValue + standardDeviation * Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2); }
export function monteCarlo<T>(iterations: number, simulate: (index: number) => T): T[] { return Array.from({ length: Math.max(0, Math.trunc(iterations)) }, (_, i) => simulate(i)); }
export function monteCarloScalar(iterations: number, simulate: (index: number) => number): { samples: number[]; mean: number; stddev: number; p05: number; p50: number; p95: number } { const samples = monteCarlo(iterations, simulate); return { samples, mean: mean(samples), stddev: stddev(samples), p05: percentile(samples, 0.05), p50: percentile(samples, 0.5), p95: percentile(samples, 0.95) }; }
export function rootMeanSquare(values: readonly number[]): number { return Math.sqrt(mean(values.map((x) => x * x))); }
